name: CI Test

on:
  pull_request:
  push:
    branches: 
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: gradle cleanAllTests
      - run: gradle jvmTest
      - run: gradle jsTest
      - run: gradle nativeTest
        continue-on-error: true
          
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: gradle cleanAllTests
      - run: gradle jvmTest
      - run: gradle jsTest
      - run: gradle nativeTest
        continue-on-error: true
          
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: gradle cleanAllTests
      - run: gradle jvmTest
      - run: gradle jsTest
      - run: gradle nativeTest
        continue-on-error: true
        
  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: gradle jvmTest
